api:
  image: registry.k8s.io/kube-apiserver:v1.27.1
  extraArgs:
    - "--feature-gates=InPlacePodVerticalScaling=true"
scheduler:
  image: registry.k8s.io/kube-scheduler:v1.27.1
controller:
  image: registry.k8s.io/kube-controller-manager:v1.27.1

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.0