{{- if .Values.init.manifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-manifests
  namespace: {{ .Release.Namespace }}
data:
  initmanifests.yaml: |-
    {{ .Values.init.manifests | nindent 4 | trim }}
{{- end }}